general.import = [
 # "~/.config/alacritty/themes/themes/zenburn.toml",
]

[env]
WINIT_X11_SCALE_FACTOR="1.0"

[font]
#normal = { family = "JetBrainsMono Nerd Font" }
normal = { family = "MesloLGS Nerd Font Propo" }
size=18

[window]
blur=true
#opacity=0.8
startup_mode="Maximized"
option_as_alt="Both"

[selection]
save_to_clipboard=true

[terminal]
osc52="CopyPaste"
